language: node_js
node_js: "6"
cache: npm

dist: xenial
addons:
  apt:
    packages:
    - wine
    - mono-devel

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
